data_acquisition:
  start_date: '2020-01-01'
  end_date: '2024-11-12'
  tickers:
    - AAPL
    - GOOGL
    - MSFT
    - AMZN
    - TSLA

preprocessing:
  moving_average_windows:
    - 5
    - 20
  fill_method: 'ffill'  # Fill method for NaN values
  columns_required:
    - Date
    - Close
