model_parameters:
  random_state: 42
  test_size: 0.2
  
training_parameters:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001

validation_thresholds:
  accuracy: 0.7
  precision: 0.7
  recall: 0.7
  f1_score: 0.7 