name: Model Training Pipeline

on:
  push:
    paths:
      - 'src/model/**'
      - 'data/mitigated/**'
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight

jobs:
  train-models:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Train Models
      run: python src/model/train_all.py
      
    - name: Run Bias Detection
      run: python src/model/check_bias.py
      
    - name: Push to Model Registry
      if: success()
      run: python src/model/push_to_registry.py 