name: CI/CD Pipeline for Airflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: airflow
          POSTGRES_PASSWORD: airflow
          POSTGRES_DB: airflow
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U airflow"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker-compose version

      - name: Build Docker Containers
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run Airflow Init
        run: |
          docker-compose -f docker-compose.yml up airflow-init

      - name: Run Tests
        run: |
          docker-compose -f docker-compose.yml up --abort-on-container-exit
        env:
          AIRFLOW__CORE__EXECUTOR: LocalExecutor

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          docker-compose -f docker-compose.yml up -d
