name: ML Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-and-validate:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: airflow
          POSTGRES_PASSWORD: airflow
          POSTGRES_DB: airflow
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Build Airflow Image
        run: |
          docker build -t airflow_custom -f docker/airflow/Dockerfile .
          
      - name: Start Airflow Services
        run: |
          docker run -d \
            --name airflow \
            -e AIRFLOW__CORE__SQL_ALCHEMY_CONN="postgresql+psycopg2://airflow:airflow@postgres/airflow" \
            -v ${{ github.workspace }}/dags:/opt/airflow/dags \
            -v ${{ github.workspace }}/data:/opt/airflow/data \
            airflow_custom

      - name: Run DAG
        run: |
          docker exec airflow airflow dags unpause stock_prediction_pipeline
          docker exec airflow airflow dags trigger stock_prediction_pipeline
