name: ML Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  model-training:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Set up DVC
        uses: iterative/setup-dvc@v1

      - name: Configure GCP Credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r modelrequire.txt
          pip install dvc[gdrive]

      - name: Pull DVC data
        run: |
          dvc pull data/dvc_tracked/AAPL_mitigated.csv
          dvc pull data/dvc_tracked/GOOGL_mitigated.csv
          dvc pull data/dvc_tracked/MSFT_mitigated.csv

      - name: Train Model
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials/latest.json
        run: |
          mkdir -p credentials
          echo '${{ secrets.GCP_CREDENTIALS }}' > credentials/latest.json
          python -m models.train

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-artifacts
          path: mlruns/
          retention-days: 90

      - name: Clean up credentials
        if: always()
        run: rm -rf credentials/
